sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dc/react-test npm test

after_success:
  - docker build -t dc/multi-client ./client
  - docker build -t dc/multi-nginx ./nginx
  - docker build -t dc/multi-server ./server
  - docker build -t dc/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker tag dc/multi-client:latest dewansh05/dockerhub:dc/multi-client
  - docker tag dc/multi-nginx:latest dewansh05/dockerhub:dc/multi-nginx
  - docker tag dc/multi-server:latest dewansh05/dockerhub:dc/multi-server
  - docker tag dc/multi-worker:latest dewansh05/dockerhub:dc/multi-worker
  - docker push dewansh05/dockerhub:dc/multi-client
  - docker push dewansh05/dockerhub:dc/multi-nginx
  - docker push dewansh05/dockerhub:dc/multi-server
  - docker push dewansh05/dockerhub:dc/multi-worker
