sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dc/react-test npm test

after_success:
  #build and push images to docker hub
  - docker build -t dc/multi-client ./client
  - docker build -t dc/multi-nginx ./nginx
  - docker build -t dc/multi-server ./server
  - docker build -t dc/multi-worker ./worker
  #login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #push images to docker hub
  - docker push dc/multi-client
  - docker push dc/multi-nginx
  - docker push dc/multi-server
  - docker push dc/multi-worker
